[CUDA_Runtime_jll]
local = "true"
version = "12.3"

[HDF5]
libhdf5 = "/opt/ohpc/pub/libs/gnu9/hdf5/1.10.8/lib/libhdf5.so"
libhdf5_hl = "/opt/ohpc/pub/libs/gnu9/hdf5/1.10.8/lib/libhdf5_hl.so"

[HDF5_jll]
libhdf5_hl_path = "/opt/ohpc/pub/libs/gnu9/hdf5/1.10.8/lib/libhdf5_hl.so"
libhdf5_path = "/opt/ohpc/pub/libs/gnu9/hdf5/1.10.8/lib/libhdf5.so"

[MPIPreferences]
__clear__ = ["preloads_env_switch"]
_format = "1.0"
abi = "OpenMPI"
binary = "system"
cclibs = []
libmpi = "libmpi"
mpiexec = "mpiexec"
preloads = []

[P4est]
libp4est = "/home/alessio/.local/lib/libp4est.so"
libsc = "/home/alessio/.local/lib/libsc.so"

[T8code]
libp4est = "/home/alessio/.local/lib/libp4est.so"
libsc = "/home/alessio/.local/lib/libsc.so"
libt8 = "/home/alessio/.local/lib/libt8.so"
